export const ACTION_TYPES = {
    FETCH_ALL: 'FETCH_ALL',
    FETCH_BY_ID: 'FETCH_BY_ID',
    SORT: 'SORT',
    SEARCH: 'SEARCH',

    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',

    GET_CART: 'GET_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    UPDATE_CART: 'UPDATE_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',

    CHECKOUT: 'CHECKOUT'
}